# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='bg_image',
            field=models.ImageField(upload_to='images/service', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0444\u043e\u043d\u0430 - 215x215'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='images/service - 190x114'),
        ),
    ]
