# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u0418\u043c\u044f \u0447\u0435\u043b\u043e\u0432\u0435\u043a\u0430')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441 \u043e\u0442\u0437\u044b\u0432\u0430')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0437\u044b\u0432',
                'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b',
            },
        ),
    ]
