# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GallerySlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0430')),
                ('image', models.ImageField(upload_to='images/slider/gallery', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u0421\u043b\u0430\u0439\u0434\u0435\u0440 \u0433\u0430\u043b\u0435\u0440\u0435\u0438',
                'verbose_name_plural': '\u0421\u043b\u0430\u0439\u0434\u0435\u0440\u044b \u0433\u0430\u043b\u0435\u0440\u0435\u0438',
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0430')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430')),
                ('image', models.ImageField(upload_to='images/slider/main', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u0413\u043b\u0430\u0432\u043d\u044b\u0439 \u0441\u043b\u0430\u0439\u0434\u0435\u0440',
                'verbose_name_plural': '\u0413\u043b\u0430\u0432\u043d\u044b\u0435 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='PartnerSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u0421\u043b\u0430\u0439\u0434 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u0430',
                'verbose_name_plural': '\u0421\u043b\u0430\u0439\u0434\u044b \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u043e\u0432',
            },
        ),
    ]
