# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_auto_20170404_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeingSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430')),
                ('image', models.ImageField(upload_to='images/slider/parners', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0434\u043b\u044f \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u0421\u043b\u0430\u0439\u0434\u0435\u0440 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u0437\u0430 \u0440\u0443\u0431\u0435\u0436',
                'verbose_name_plural': '\u0421\u043b\u0430\u0439\u0434\u0435\u0440\u044b \u043e\u0442\u043f\u0430\u0440\u0430\u0432\u043a\u0438 \u0437\u0430 \u0440\u0443\u0431\u0435\u0436',
            },
        ),
        migrations.AlterField(
            model_name='galleryslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/slider/gallery', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430 - \u043f\u0440\u043e\u043f\u043e\u0440\u0446\u0438\u0438 1\u04451'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=models.ImageField(upload_to='images/slider/main', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430 1300x390px'),
        ),
        migrations.AlterField(
            model_name='partnerslider',
            name='image',
            field=models.ImageField(upload_to='images/slider/partners', verbose_name='\u041b\u043e\u0433\u043e \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u043e\u0432 - 103x103px \u043c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u043e'),
        ),
    ]
