# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-21 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_auto_20170424_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foreingslider',
            options={'verbose_name': '\u0421\u043b\u0430\u0439\u0434\u0435\u0440 \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u0437\u0430 \u0440\u0443\u0431\u0435\u0436', 'verbose_name_plural': '\u0421\u043b\u0430\u0439\u0434\u0435\u0440\u044b \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438 \u0437\u0430 \u0440\u0443\u0431\u0435\u0436'},
        ),
        migrations.AlterField(
            model_name='foreingslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/slider/parners', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/slider/main', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430 1300x390px'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043b\u0430\u0439\u0434\u0430'),
        ),
    ]
