# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 14:42
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0434\u043b\u044f \u0442\u0435\u043a\u0441\u0442\u0430')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e \u043d\u0430\u0441')),
                ('partner_title', models.CharField(default='\u041d\u0430\u0448\u0438 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u044b', max_length=225, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432\u0441\u043c\u0435\u0441\u0442\u043e "\u041d\u0430\u0448\u0438 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u044b"')),
                ('partner_text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043a\u043e\u043c "\u041d\u0430\u0448\u0438 \u043f\u0430\u0440\u0442\u043d\u0435\u0440\u044b"')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430')),
            ],
            options={
                'verbose_name': '\u041e \u043d\u0430\u0441',
                'verbose_name_plural': '\u041e \u043d\u0430\u0441',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='\u0420\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u044b', max_length=225, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('time', models.CharField(max_length=255, verbose_name='\u0420\u0435\u0436\u0438\u043c \u0440\u0430\u0431\u043e\u0442\u044b')),
                ('email', models.CharField(max_length=225, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=225, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u044b')),
                ('address', models.CharField(max_length=225, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('latitude', models.CharField(default='42.8746212', max_length=225, verbose_name='\u0414\u043e\u043b\u0433\u043e\u0442\u0430')),
                ('longitude', models.CharField(default='74.5697617', max_length=225, verbose_name='\u0428\u0438\u0440\u043e\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b',
            },
        ),
    ]
