# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 11:56
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='longitude',
        ),
        migrations.AddField(
            model_name='contacts',
            name='location',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='\u041c\u0430\u0440\u043a\u0435\u0440 \u043d\u0430 \u043a\u0430\u0440\u0442\u0435'),
        ),
    ]
