# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-24 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20170407_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='\u041f\u0435\u0440\u0432\u043e\u0435 \u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430 - 490x300px'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='\u0412\u0442\u043e\u0440\u043e\u0435 \u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430 - 490x300px'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='\u0422\u0440\u0435\u0442\u044c\u0435 \u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0434\u043b\u044f \u0441\u043b\u0430\u0439\u0434\u0435\u0440\u0430 - 490x300px'),
        ),
    ]
